### ISSUE TITLE
Unstable connections

### ISSUE THREAD

**Issue by DanielEWeeks** [kristofg/rifec#17]
With a Connect X2 4GB card on a Mac OS X 10.10.5 machine, this connected successfully only once, getting far enough to die with an "Unsupported transfer mode" error message.  But on many subsequent attempts, it failed to connect, with the card connecting instead to the central server run by Eye-Fi.

Is there some way to instruct the card to always connect to the local host first? 

2016-09-08 03:06:58Z   22300   TRACE Request headers: $VAR1 = [
          'Connection: Close',
          'Accept: text/xml, application/soap',
          'Host: api.eye.fi',
          'User-Agent: Eye-Fi Card/5.2010',
          'Content-Length: 412',
          'SOAPAction: "urn:StartSession"'
        ];
2016-09-08 03:06:58Z   22300    INFO StartSession from 'dw eyefi' (00185628b7ef)
2016-09-08 03:06:58Z   22300   TRACE StartSession: $VAR1 = {
          'macaddress' => '00185628b7ef',
          'transfermode' => '16387',
          'transfermodetimestamp' => '1473303454',
          'cnonce' => '1eb4ee3f75a06a113d638a28fbafdc6f'
        };
2016-09-08 03:06:58Z   22300 WARNING Died in request handling: Unsupported transfermode '16387' from card 'dw eyefi' (00185628b7ef), See TROUBLESHOOTING.txt for info about what this means at ./rifec.pl line 664.

**Comment by kristofg** [comment]
Hi,

Yes, you can (or at least, you could) configure your card to upload to a server on the local network only, not to the cloud.  Doing so would likely solve your transfermode problem as well.

I haven't used the Eye-Fi desktop program in years, so I I can't provide step-by-step on how to do this, but I suggest you search [here](https://x2help.eyefi.com/hc/en-us).  This may also have changed with the [end-of-life-process of X2 products](http://x2migration.eyefi.com/hc/en-us/articles/224155567-UPDATE-Information-Regarding-End-of-Life-EOL-of-X2-and-Prior-Generation-Products).

**Comment by DanielEWeeks** [comment]
Thank you.  In case it might help others, it turned out that using the EyeFi Center software to configure the card, I had to turn off both

1) uploading to Eye-Fi View
2) uploading to Flicker

before the card would preferentially and reliably connect to the local eyefiserver.
